#!/usr/bin/env bash
# script that transfers a file from our client to a server
args=("$@");
if ((${#args[@]} == 4));
then
	scp -o StrictHostKeychecking=no -i "${args[3]}" "${args[0]}" "${args[2]}"@"${args[1]}":~/
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
