#!/usr/bin/env bash
# script that configures a new Ubuntu machines Nginx server redirection
sudo apt-get update
sudo apt -y install nginx
inside_text="<!DOCTYPE html><html><body><h1>Hello World!</h1></body></html>"
echo "${inside_text}" | sudo tee /var/www/html/index.html
redirect="server_name _;\nlocation \/redirect_me {\nreturn 301;\n}"
sudo sed -i "s/server_name _;/$redirect/" /etc/nginx/sites-available/default
service nginx reload
