#!/usr/bin/env bash
# script that adds a custom header to an Ubuntu machine with nginx
new_header="\n  add_header X-Served-By \"\$hostname\";\n"
sudo sed -i "24s/^$/$new_header/" /etc/nginx/sites-available/default
sudo service nginx restart
