#!/usr/bin/env bash
# script that installs HAProxy on a new Ubuntu machine and cofiigures it
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt install -y haproxy=2.0.\*

# enable initiation via script
word='ENABLED=1'
sed -i "5s/^$/$word/" /etc/default/haproxy

# copy the configuration file and edit the copied version
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
text2="Frontend www
	bind *:80
	mode http
	balance roundrobin
	default_backend myservers

Backend myservers
	mode http
	balance roundrobin
	server server1 100.25.167.201:80
	server server2 54.162.225.169:80"
sudo echo '$text2' >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
