#!/usr/bin/env bash
# Script that configures a server to listen to a specific port
pkill -HUP nginx
rm /usr/sbin/nginx
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
