#!/usr/bin/env bash
# Script that configures a server to listen to a specific port
pkill -HUP nginx
rm /usr/sbin/nginx
rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
