#!/usr/bin/env bash
# Bash script that gives you information about the school file.
name_file='school'
if [ -e $name_file ]
then
    echo "$name_file file exists"
    if [ -s $name_file ]
    then
	echo "$name_file file is not empty"
    else
	echo "$name_file file is empty"
    fi
    if [ -f $name_file ]
    then
	echo "$name_file is a regular file"
    fi
else
    echo "$name_file file does not exist"
fi
